version: "3.3"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - crawler_gold_currency
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - crawler_gold_currency
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - crawler_gold_currency
  opa:
    image: openpolicyagent/opa:latest-debug
    restart: always
    ports:
      - "8181:8181"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - run
      - --server
      - --log-level=debug
      - --set=services.api.url=http://host.docker.internal:8000
      - --set=bundles.api.service=api
      - --set=bundles.api.resource=/api/opa/rules
      - --set=bundles.api.polling.min_delay_seconds=5
      - --set=bundles.api.polling.max_delay_seconds=15
volumes:
  redis_volume_data:
  redis_insight_volume_data:
networks:
  crawler_gold_currency:
    driver: bridge